# -*- coding: utf-8 -*-
"""gradio_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_3OUwgJmgQjTZwzkqWWU1hYM5Jaz5D3
"""

import torch
import gradio as gr
from diffusers import StableDiffusionPipeline, UNet2DConditionModel
from peft import PeftModel
import random
import warnings
warnings.filterwarnings("ignore")

# Configuración
device = "cuda"
model_id = "runwayml/stable-diffusion-v1-5"
lora_id = "jearx85/medisyn-lora"

print("Cargando modelo...")

# Cargar modelo
unet = UNet2DConditionModel.from_pretrained(
    model_id, subfolder="unet", torch_dtype=torch.float16
)
unet = PeftModel.from_pretrained(unet, lora_id)
unet = unet.to(torch.float16).to(device)

pipeline = StableDiffusionPipeline.from_pretrained(
    model_id, unet=unet, torch_dtype=torch.float16, safety_checker=None
).to(device)

pipeline.enable_attention_slicing()

print("Modelo listo")

# Función de generación
def generate(disease, custom, steps, guidance, seed):
    prompts = {
        "Normal": "medical normal healthy chest x-ray, clear lungs",
        "Neumonía Leve": "medical chest x-ray mild pneumonia",
        "Neumonía Moderada": "medical chest x-ray pneumonia, lung infection",
        "Neumonía Severa": "medical chest x-ray severe pneumonia"
    }

    prompt = prompts[disease]
    if custom: prompt += f", {custom}"
    prompt += ", high quality radiograph"

    if seed == -1:
        seed = random.randint(0, 2**32-1)

    gen = torch.Generator(device).manual_seed(int(seed))

    with torch.inference_mode():
        img = pipeline(
            prompt, num_inference_steps=int(steps),
            guidance_scale=float(guidance), generator=gen
        ).images[0]

    info = f"**Prompt:** {prompt}\n**Seed:** {seed}"
    return img, info

# Interfaz
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("#MediSynth - Generador de Imágenes Médicas")
    gr.Markdown("Solo para investigación y educación")

    with gr.Row():
        with gr.Column():
            disease = gr.Dropdown(
                ["Normal", "Neumonía Leve", "Neumonía Moderada", "Neumonía Severa"],
                value="Neumonía Moderada", label="Tipo"
            )
            custom = gr.Textbox(label="Descripción adicional", lines=2)

            with gr.Accordion("Avanzado", open=False):
                steps = gr.Slider(20, 100, 50, step=5, label="Steps")
                guidance = gr.Slider(1, 15, 7.5, step=0.5, label="Guidance")
                seed = gr.Number(-1, label="Seed (-1 = random)")

            btn = gr.Button("Generar", variant="primary", size="lg")

        with gr.Column():
            img_out = gr.Image(label="Resultado", type="pil")
            info_out = gr.Markdown()

    btn.click(generate, [disease, custom, steps, guidance, seed], [img_out, info_out])

    gr.Markdown("""
    ---
    ### Proyecto
    - **Modelo:** [jearx85/medisyn-lora](https://huggingface.co/jearx85/medisyn-lora)
    - **Base:** Stable Diffusion 1.5 + LoRA
    - **Dataset:** Chest X-Ray Pneumonia
    """)

demo.launch(
    share=True,
    debug=True,
    show_error=True
)